engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
    config:
      config: rook/assets/.eslintrc
  pep8:
    enabled: true
  fixme:
    enabled: false
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.py"
  - "rook/assets/**.js"
  - "rook/assets/**.jsx"
exclude_paths:
- ".*"
- "**.pyc"
- "**.gz"
- "env/"
- "tests/"
- "rook/assets/images/"
- "rook/assets/vendor/"
- "rook/assets/node_modules/"
- "rook/assets/javascripts/dist/"
- "rook/migrations"
- "docs/"
